metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_minitrain2017_002.json
    dataset_dir: /Users/liuhui29/Downloads/coco_001
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017_01_02.json
    dataset_dir: /Users/liuhui29/Downloads/coco_001

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json
