metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/dota_debug.json
    dataset_dir: dataset/dota

EvalDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/dota_debug.json
    dataset_dir: dataset/dota

TestDataset:
  !ImageFolder
    anno_path: annotations/dota_debug.json
