_BASE_: [
  './_base_/models/faster_rcnn_dcn_r50_fpn_pssdet.yml',
  './_base_/optimizers/rcnn_3x.yml',
  './_base_/datasets/coco.yml',
  './_base_/readers/faster_fpn_reader_pssdet.yml',
  './_base_/runtime.yml',
]
