_BASE_: [
  './_base_/models/faster_rcnn_dcn_r50_fpn_pssdet_debug.yml',
  './_base_/optimizers/rcnn_1x_debug.yml',
  './_base_/datasets/coco_mini.yml',
  './_base_/readers/faster_fpn_reader_pssdet_debug.yml',
  './_base_/runtime_debug.yml',
]
