_BASE_: [
  './_base_/models/faster_rcnn_dcn_r50_fpn_pssdet_roadsign_1.yml',
  './_base_/optimizers/rcnn_1x.yml',
  './_base_/datasets/roadsign.yml',
  './_base_/readers/faster_fpn_reader_pssdet_1.yml',
  './_base_/runtime.yml',
]
