_BASE_: [
  './_base_/models/s2anet_r50_fpn.yml',
  './_base_/optimizers/rcnn_1x.yml',
  './_base_/datasets/coco_debug.yml',
  './_base_/readers/faster_fpn_reader_s2anet.yml',
  './_base_/runtime.yml',
]
